# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Agung.xyz
email: goahead@spam4.me
description: > # this means to ignore newlines until "baseurl:"
  The site of ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://agung.xyz" # the base hostname & protocol for your site
#enforce_ssl: agung.xyz
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
